Traceback (most recent call last):
  File "/home/ebn/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ebn/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ebn/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ebn/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ebn/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ebn/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Cria a pasta "reports" se ela nÃ£o existir
pathlib.Path("reports").mkdir(exist_ok=True)

# Coleta nome do repositÃ³rio e nome do usuÃ¡rio
repo_name = input("Informe o nome do repositÃ³rio: ")
repo_url = input("Informe a URL do repositÃ³rio: ")
user_name = input("Informe seu nome: ")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      2[0m pathlib[38;5;241m.[39mPath([38;5;124m"[39m[38;5;124mreports[39m[38;5;124m"[39m)[38;5;241m.[39mmkdir(exist_ok[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      4[0m [38;5;66;03m# Coleta nome do repositÃ³rio e nome do usuÃ¡rio[39;00m
[0;32m----> 5[0m repo_name [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mInforme o nome do repositÃ³rio: [39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      6[0m repo_url [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mInforme a URL do repositÃ³rio: [39m[38;5;124m"[39m)
[1;32m      7[0m user_name [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mInforme seu nome: [39m[38;5;124m"[39m)

File [0;32m~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py:1190[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1188[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1189[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1190[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1191[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1192[0m     [38;5;28mstr[39m(prompt),
[1;32m   1193[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1194[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1195[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1196[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

